import type { Metadata } from "next";
import "./globals.css";
import { getAuthenticatedUser } from "@/auth";
import Link from "next/link";
import { LogoutButton } from "./components/LogoutButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const user = await getAuthenticatedUser();

  return (
    <html lang="en">
      <body className="antialiased bg-gray-50 text-gray-900">
        <header className="max-w-5xl mx-auto px-4 py-4 border-b border-gray-200">
          <nav className="flex items-baseline justify-between">
            <Link className="text-xl font-semibold" href={"/"}>
              My App
            </Link>
            <div className="flex items-center gap-x-6">
              {user ? (
                <>
                  <p className="text-sm font-medium">
                    Welcome,{" "}
                    <Link
                      className="font-medium text-blue-600 hover:underline"
                      href={"/profile"}
                    >
                      {user.username}
                    </Link>
                  </p>
                  <LogoutButton />
                </>
              ) : (
                <>
                  <Link
                    href={"/login"}
                    className="text-sm font-medium text-blue-600 hover:underline"
                  >
                    Login
                  </Link>
                  <Link
                    href={"/register"}
                    className="text-sm font-medium text-blue-600 hover:underline"
                  >
                    Register
                  </Link>
                </>
              )}
            </div>
          </nav>
        </header>
        <main className="max-w-5xl mx-auto px-4 py-6">{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
