import type { Metadata } from "next";
import "./globals.css";
import { getAuthenticatedUser } from "@/auth";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const user = await getAuthenticatedUser();

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <header className="max-w-5xl mx-auto px-4 py-2">
          <nav className="flex gap-x-8 justify-end">
            {user ? (
              <>
                <p>{user}</p>
                <button>Logout</button>
              </>
            ) : (
              <>
                <Link href={"/login"}>Login</Link>
                <Link href={"/register"}>Register</Link>
              </>
            )}
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
