import type { Metadata } from "next";
import "./globals.css";
import { getAuthenticatedUser } from "@/auth";
import Link from "next/link";
import { LogoutButton } from "./components/LogoutButton";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const user = await getAuthenticatedUser();

  return (
    <html lang="en" className={inter.className}>
      <body className="antialiased bg-gray-50 text-gray-900">
        <div className="max-w-5xl mx-auto w-full border-x border-gray-200 min-h-screen">
          <header className="py-6 px-4 border-b border-gray-200">
            <nav className="flex items-baseline justify-between">
              <Link className="text-lg font-medium" href={"/"}>
                Notes App
              </Link>
              <div className="flex items-baseline gap-x-6">
                {user ? (
                  <>
                    <p className="">
                      Welcome,{" "}
                      <Link
                        className="font-medium text-blue-600 hover:underline"
                        href={"/profile"}
                      >
                        {user.username}
                      </Link>
                    </p>
                    <LogoutButton />
                  </>
                ) : (
                  <>
                    <Link
                      href={"/login"}
                      className="text-sm font-medium text-blue-600 hover:underline"
                    >
                      Login
                    </Link>
                    <Link
                      href={"/register"}
                      className="text-sm font-medium text-blue-600 hover:underline"
                    >
                      Register
                    </Link>
                  </>
                )}
              </div>
            </nav>
          </header>
          <main className="">{children}</main>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
